name: service-discovery
type: service
maxMemory: 512
segment: external
ports:
  - 80:80
environment:
  - CONSUL_URI=service-discovery.dev.williamhill.internal:8500
  - CONSUL_NAME=dev-service-discovery
healthCheck:
  endpoint: /health
  timeoutSeconds: 1
  intervalSeconds: 30